New Commit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,3 +18,10 @@ jobs:
         run: ./gradlew build
       - name: Run Test with Gradle Wrapper
         run: ./gradlew test
+      - name: Build and Run Tests
+        run: # execute your tests generating test results
+          - name: Publish Test Report
+            uses: mikepenz/action-junit-report@v4
+            if: success() || failure() # always run even if the previous step fails
+            with:
+              report_paths: '**/build/test-results/test/TEST-*.xml'
